### ISSUE TITLE
Bug: ERR_CLEARTEXT_NOT_PERMITTED

### ISSUE THREAD

**Issue by pacjo** [jonschoning/espial-share-android#3] opened 2023-09-03 10:31 UTC
I found your project through noted.lol, but I can't get it fully working.

Web interface works fine, but app refuses to work by throwing `ERR_CLEARTEXT_NOT_PERMITTED` error. The same url works when using it in a regular browser (recording below).

One thing is that I haven't set API key as I can't find it anywhere.

For now I'm sharing a link to the video, as I can't get it to upload. Will try again later.
https://photos.app.goo.gl/8PmvHbDMZZjTgg6n9

**Comment by jonschoning** [comment] 2023-09-03 18:49
Ahh, I see it you're just serving espial directly over HTTP instead of HTTPS, which the webview in android doesn't like.  I'll see if there's a workaround.  However you could also just server espial over HTTPS to fix it immediately in the meantime.  I use cloudflare for https://esp.ae8.org/ , but if you want to do it completely locally, maybe something like https://caddyserver.com/ to reverse proxy espial might be a simple choice (there's also always nginx but it's a pain to configure).

**Comment by pacjo** [comment] 2023-09-04 04:01
Thanks

**Comment by srd424** [comment] 2023-09-11 17:44
Looks like it might be possible to twiddle some options somewhere to allow this? https://stackoverflow.com/questions/52707918/webview-showing-err-cleartext-not-permitted-although-site-is-https

**Comment by srd424** [comment] 2023-09-11 21:20
> Looks like it might be possible to twiddle some options somewhere to allow this? https://stackoverflow.com/questions/52707918/webview-showing-err-cleartext-not-permitted-although-site-is-https

After an evening of messing around trying to rebuild the apk, I can confirm this works :)

**Comment by jonschoning** [comment] 2023-12-01 16:25
should be resolved in Release 0.0.6

**Closed as completed by jonschoning** 2023-12-01 16:25 UTC
